### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Marcdup1** [Ks89/Angular2-webpack2-skeleton#1]
Hello,

when trying to run `npm start` I get the following error:
```keywords if/then/else require v5 option
 10% building modules 4/4 modules 0 activeevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

Please help me to fix this.

**Comment by Ks89** [comment]
Hi!
You have another running node process or something else that is using the same address + port.
I suggest to restart your pc or to change port 8080 in all config files with another one.

Which OS are you using? 
Did you kill all other node processes (via task manager/activity monitor or command line)?

**Comment by Ks89** [comment]
Here you can find all 8080's occurrences in this repository

https://github.com/Ks89/Angular2-webpack2-skeleton/search?utf8=%E2%9C%93&q=8080

**Comment by Marcdup1** [comment]
Oh! I see, 8080 was in use. It works perfectly, thank you so much.
This is a great repo, I found so many issues when trying to install bootstrap.

**Comment by Ks89** [comment]
thank u :)
