### ISSUE TITLE
bootstrap failling to load

### ISSUE THREAD

**Issue by joelmuskwe** [Ks89/Angular2-webpack2-skeleton#10]
getting the following error:

WARNING in ./src/polyfills.ts
[9, 9]: object access via string literals is disallowed

 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/polyfills.ts

WARNING in ./src/vendor.ts
[23, 29]: file should end with a newline

 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/vendor.ts

WARNING in ./src/admin/admin.module.ts
[10, 34]: " should be '

 @ ./src/admin.ts 4:21-52
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/admin.ts

WARNING in ./src/admin/pages/dashboard/dashboard.component.ts
[10, 17]: block is empty

 @ ./src/admin/admin.module.ts 17:28-76
 @ ./src/admin.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/admin.ts

WARNING in ./src/admin/common/services/services.ts
[17, 28]: file should end with a newline

 @ ./src/admin/admin.module.ts 19:17-54
 @ ./src/admin.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/admin.ts

ERROR in ./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":4,"useFlexbox":true,"extractStyles":false,"styleLoaders":["style","css","postcss","sass"],"styles":["mixins","normalize","print","reboot","type","images","code","grid","tables","forms","buttons","animation","dropdown","button-group","input-group","custom-forms","nav","navbar","card","breadcrumb","pagination","jumbotron","alert","progress","media","list-group","responsive-embed","close","tags","modal","tooltip","popover","carousel","utilities"],"scripts":["alert","button","carousel","collapse","dropdown","modal","popover","scrollspy","tab","tooltip","util"],"configFilePath":"c:/Work/examples/angular2-webpack2-skeleton/.bootstraprc","bootstrapPath":"c:/Work/examples/angular2-webpack2-skeleton/~/bootstrap","bootstrapRelPath":"../bootstrap"}!./~/bootstrap-loader/no-op.js
Module build failed:
undefined
^
      File to import not found or unreadable: ../bootstrap/scss/_animation.
Parent style sheet: stdin
      in c:\Work\examples\angular2-webpack2-skeleton\node_modules\bootstrap-loader\no-op.js (line 14, column 1)
 @ ./~/style-loader!./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":4,"useFlexbox":true,"extractStyles":false,"styleLoaders":["style","css","postcss","sass"],"styles":["mixins","normalize","print","reboot","type","images","code","grid","tables","forms","buttons","animation","dropdown","button-group","input-group","custom-forms","nav","navbar","card","breadcrumb","pagination","jumbotron","alert","progress","media","list-group","responsive-embed","close","tags","modal","tooltip","popover","carousel","utilities"],"scripts":["alert","button","carousel","collapse","dropdown","modal","popover","scrollspy","tab","tooltip","util"],"configFilePath":"c://Work//examples//angular2-webpack2-skeleton//.bootstraprc","bootstrapPath":"c://Work//examples//angular2-webpack2-skeleton//~//bootstrap","bootstrapRelPath":"..//bootstrap"}!./~/bootstrap-loader/no-op.js 4:14-1094
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
 @ ./~/bootstrap-loader/loader.js
 @ ./src/vendor.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/vendor.ts

ERROR in [default] c:\Work\examples\angular2-webpack2-skeleton\src\admin\admin.module.ts:15:28
Cannot find module 'angular2-ladda'.

Error: Module build failed: 
undefined
^
      File to import not found or unreadable: ../bootstrap/scss/_animation.
Parent style sheet: stdin
      in c:\Work\examples\angular2-webpack2-skeleton\node_modules\bootstrap-loader\no-op.js (line 14, column 1)

**Comment by Ks89** [comment]
Thank u for this issue. It happens because bootstrap-loader is not compatibile with Bootstrap 4 alpha 6. So I have to force bootstrap alpha 5, at the moment.
Check in a couple of minutes my new commit on master branch with the solution.

**Comment by Ks89** [comment]
Now it should work. Can you confirm?
