### ISSUE TITLE
bower_components

### ISSUE THREAD

**Issue by Marcdup1** [Ks89/Angular2-webpack2-skeleton#16]
Good day,

I want to install a component that's only available through bower: http://timetablejs.org/
How can I get it to work in this project and make ```Timetable``` available in a component?

**Comment by Ks89** [comment]
Hello!
This is a good question.

First of all this is not angular module/component/directive, so be careful if you want to use it with Angular.

I talked with many angular developers and I never found a guy that is using bower. I think that npm is the 'standard de facto' for Angular2. 

My template, but also all other templates that I found on github are using npm.

The best thing that you can do is to open an issue on timetable's github page to ask for an npm release. 
npm is official, bower is an alternative.
Yesterday, I published a library to npm (not on bower) and it is extremely simple.

If you need support while opening an issue on timetable's page, link this issue.

**Comment by Ks89** [comment]
Oh wait, there is an open issue about this problem https://github.com/Grible/timetable.js/issues/1

**Comment by Marcdup1** [comment]
Thank you for your reply.  

Ooh I see,  so I won't be able to use it if it's not installed through npm? If I can use it can you please direct me on how to get it to work?

Also, let's say I wanted to use lodash (installed through npm)  in a component? How can I use it in a component?

**Comment by Ks89** [comment]
Yes, all templates/skeletons use npm so you have to wait for an npm release.

I used underscorejs with angularJS 1 and I created a factory to expose "_" to angular in a standard way.
I never tried to use lodash in a component, but only inside an Angular2 unit test.
Check here for an example: /blob/4b0885779745e7c94e20a011c8edada442a0ac16/src/app/common/services/contact.service.spec.ts.

If you have problems with the previous example, you can try to use lodash as localstorage/sessionstorage, accessing the "window" object, for instance `window._.isError();`.

**Comment by Marcdup1** [comment]
Thank you so much for your help.  I'm going to look into it.
